#define NEIGHBOUR_EMPTY ~0
#define NEIGHBOUR_NEGATIVE_X 0
#define NEIGHBOUR_NEGATIVE_Y 1
#define NEIGHBOUR_NEGATIVE_Z 2
#define NEIGHBOUR_POSITIVE_X 3
#define NEIGHBOUR_POSITIVE_Y 4
#define NEIGHBOUR_POSITIVE_Z 5

#define NORMAL_X_POS 0
#define NORMAL_X_NEG 1
#define NORMAL_Y_POS 2
#define NORMAL_Y_NEG 3
#define NORMAL_Z_POS 4
#define NORMAL_Z_NEG 5
